
'''
f=open("C:\\Users\\Dell\\Desktop\\1.txt","r")
print(f.read())
'''
'''
f=open("F:\\wallpapers\\35-Latest-HD-Game-Wallpapers-For-Download-2.jpg","r+b")
print(f.read())
'''
'''
f=open("C:\\Users\\Dell\\Desktop\\1.txt","r")
print(f.read(10))
'''
'''
f=open("C:\\Users\\Dell\\Desktop\\python\\tax.py","r")
print(f.readline(5))
'''
'''
f=open("C:\\Users\\Dell\\Desktop\\python\\tax.py","r")
print(f.readline())
'''